jbergstroem/hadolint-gh-action

- lib/jq.sh
- test/unit.sh
> fix: don't emit markdown in annotations

- README.md
The readme contained a reference to a link, but the link was nowhere to be found.
Spotted by @chuma9615.
> doc: fix missing link to hadolint

- test/e2e.sh
We can now invoke it directly if `bash_unit` is installed:
```bash
$ test/e2e.sh
Running tests in test/e2e.sh
Running test_annotate... SUCCESS ✓
Running test_custom_config... SUCCESS ✓
Running test_custom_output_format... SUCCESS ✓
Running test_custom_path... SUCCESS ✓
Running test_default_path... SUCCESS ✓
Running test_default_path_with_dockerfile... SUCCESS ✓
Running test_disable_annotate... SUCCESS ✓
Running test_output_with_nonzero_exit... SUCCESS ✓
Running test_override_errorlevel... SUCCESS ✓
Running test_version_output... SUCCESS ✓
```
> test/e2e: make test executable

- lib/hadolint.sh
- lib/main.sh
Newer versions of `shellcheck` notices when aliases are used in the same parsing context, exposing the alias hack used to invoke custom hadolint paths.
The proper solution to allowing custom paths is simpler than that; just read it from environment.
As part of this, switch from `:=` notation to `:-` for "set if empty".
> fix: ensure HADOLINT_PATH is available where used

- lib/main.sh
- test/e2e.sh
- test/fixtures/Dockerfile-valid
If `error_level` is set to 2, any output from hadolint should be seen as an error. Since hadolint emits an array when output is set to json, this is seen as our happy path.
Fixes: https://github.com/jbergstroem/hadolint-gh-action/issues/24
> main: error check against json array

- README.md
- lib/validate.sh
- test/unit.sh
In Hadolint `2.5.0` the sonarqube formatter was added. This allows us to output it as part of running CI.
> Support Sonarqube as output formatter

- hadolint.sh
No need to disable the code analyzer since we can tell it where to look. In addition to this, you need to tell shellcheck to follow includes by passing `-x` in commandline or passing all source files.
> fix: tell shellcheck where to find source file

- .github/workflows/test-action.yml
A dollar sign snuck in, making the point that not being able to dynamically test actions as part of a PR flow leads to errors.
> fix: typo in action test

- USAGE.md
on the with keywork we have Schema validation: Incompatible types. Required one of: object, string. Actual: array.
so we need to remove the -
> docs: correct usage.md examples

- .github/workflows/lint-actionlint.yml
- .github/workflows/lint-prettier.yml
- .github/workflows/lint-shellcheck.yml
- .github/workflows/lint-shfmt.yml
- .github/workflows/test-action.yml
- .github/workflows/test.yml
- README.md
- USAGE.md
Mostly to stay current and the potential upside of bash `5.0` -> `5.1`.
> chore: update to a newer github actions vm

- .github/workflows/lint-actionlint.yml
- .github/workflows/lint-prettier.yml
- .github/workflows/lint-shfmt.yml
- .github/workflows/test.yml
- bash_unit `2.0.0`
- shfmt `3.5.1`
- actionlint `1.3.18`
Additionally, invoke prettier (which always uses latest) via Node 18.
> chore: update lint dependencies

- test/e2e.sh
This doesn't provide a human readable output for all errors, but likely the ones that will be caught by a human.
Fixes: https://github.com/jbergstroem/hadolint-gh-action/issues/12
> chore: improve test suite error output

- .github/workflows/lint.yml
- .github/workflows/test.yml
Until jobs support event triggers or workflows have better grouping, fighting for seconds of CI time isn't worth it.
> chore: remove per-job triggers

- .github/renovate.json
- .github/workflows/lint.yml
- .github/workflows/test-e2e.yml
- .github/workflows/test.yml
- action.yml
1. Split action (read: e2e) tests into its own file
2. Refactor how shfmt is downloaded - renovatebot should pick it up now
3. Same as above but for bash_unit
> feat: refactor tests

- .github/renovate.json
- .github/workflows/lint.yml
shfmt is the only tool that currently outputs differently as part of the renovate version matching pattern - tell it that it is optional.
> fix: standardize curl options and make output optional

- lib/main.sh
If run as a composite action, we need to rely on `GITHUB_ACTION_PATH` which defaults to unset (read: not in a composite action).
> fix: resolve path to problem matcher

- .github/renovate.json
Renovate now updates both the action as well as README as part of bumping the dependency. Also, make the topic more human readable.
> feat: update README via renovate

- .github/workflows/test-e2e.yml
This creates unnecessary noise for the glob e2e test across all PRs. Also, update the action path to cover `$self`.
> fix: don't annotate e2e tests

- .github/workflows/lint.yml
This shaves about 10 seconds (~40%) off the runtime. It is achieved by using the native github container action and downloading the latest config instead of mounting volumes via a DinD approach.
> feat: run renovate config validation via docker

- .github/renovate.json
This should allow renovatebot to properly update the tag.
> fix: remove "v" from bash_unit version

- .github/workflows/lint.yml
- .github/workflows/test-e2e.yml
- .github/workflows/test.yml
This way I don't have to manage updates as frequent.
> chore: switch to majors for stable actions

- .github/workflows/lint.yml
- .github/workflows/test-e2e.yml
- action.yml
- install.sh
Problem
When one wants to use hadolint-gh-action multiple times, an error is raised because the bin directory already exists, see https://github.com/jbergstroem/hadolint-gh-action/issues/134
Solution
Use option -p of mkdir
Fixes #134
> fix: don't download hadolint twice

- .github/workflows/lint.yml
Due to changes in how github treats internal downloads, the config
failed to be downloaded correctly.
Switch to using the javascript package instead of the docker container.
Surprisingly, also much faster (~45s -> 10s).
> fix: validate renovate config

- .github/workflows/lint.yml
- README.md
- USAGE.md
- lib/main.sh
Update examples to use latest versions of actions so its more friendly for copy pasting.
Also, check for typos in CI.
> chore(docs): update examples

- install.sh
The extra space made the debug string into a plain string, always being shown.
> fix: remove space in debug output

- .github/workflows/test-e2e.yml
- install.sh
- lib/hadolint.sh
We now remove artifacts from the version command, avoiding mismatches based on what is provided (eg: `2.9.0`) and what hadolint responds with (`2.9.0-no-git`) in certain versions.
Also, add e2e tests to cover these and refactor version checking.
> fix: stricter version parsing

- install.sh
For certain self-hosted runners we need sudo for write permissions to `/usr/local/bin`.
Closes: https://github.com/jbergstroem/hadolint-gh-action/issues/144
> fix: use sudo to move binary to `/usr/local/bin`
