README.md

The example previously provided never worked anyway.

doc: Update usage

---

lib/jq.sh

Hopefully makes it easier for people eager to understand better what we're trying to achieve.

doc: link to array issue in code

---

README.md
action.yml
lib/hadolint.sh
lib/main.sh
test/e2e.sh

Fixes: https://github.com/jbergstroem/hadolint-gh-action/issues/13

feature: support custom hadolint path

---

.github/workflows/lint.yml

feat: shfmt 3.3.1

---

.github/workflows/lint.yml
test/unit.sh

Remove lint ignores for shellcheck that were missed in 0d7df0c.

fix: shellcheck source for test inclusions

---

test/e2e.sh

Fixes: https://github.com/jbergstroem/hadolint-gh-action/issues/34

feat: test multiple dockerfiles as input

---

README.md
USAGE.md
action.yml

A first iteration of improving usage documentation.
Fixes: https://github.com/jbergstroem/hadolint-gh-action/issues/43

doc: add USAGE.md

---

.github/workflows/lint.yml
.github/workflows/test-action.yml
.github/workflows/test.yml
action.yml

This should (hopefully) make execution in actions and tests more robust by making sure that things are only continued on success.
Still not sure on curl vs wget, but at least we're consistent.

feat: switch to wget and unify execution

---

.github/workflows/test-action.yml

Again, point made that missing PR test limitations raises issues.

fix: repo path url

---

.github/workflows/lint-actionlint.yml
.github/workflows/lint-prettier.yml
.github/workflows/lint-shellcheck.yml
.github/workflows/lint-shfmt.yml
.github/workflows/test-action.yml
.github/workflows/test.yml

Update versions for:
- actions
- third parties
..also, change when they fire.

feat: update all ci dependencies

---

.github/workflows/lint.yml

Move the filtering logic from github actions to the detect changes script.

fix: only act on specific lint file changes

---

.github/dependabot.yml
.github/matcher-actionlint.json
.github/matcher-shellcheck.json
.github/renovate.json
.github/workflows/lint.yml
action.yml

This brings the following improvements:
1. Faster updates
2. Keep lint and test dependencies up to date
3. Keep hadolint up to date
Fixes: https://github.com/jbergstroem/hadolint-gh-action/issues/98
Closes: https://github.com/jbergstroem/hadolint-gh-action/pull/96

feat: use renovatebot

---

README.md
lib/main.sh
lib/validate.sh

Support all known formats in hadolint.

feat: support more output formats

---

.github/renovate.json

1. Improve `extractVersionTemplate` so Hadolint is picked up
2. Update `messageTopic` and `messageExtra` to improve titles

fix: renovate improvements

---

README.md

I would have preferred renovatebot helping out here, but that implies I need to self-host to run commands safely. Something like this should work:
```json
"postUpgradeTasks": {
"fileFilters": ["README.md"],
"commands": [
"sed -ie 's/`{{{currentVersion}}}`/`{{{newVersion}}}/g' README.md"
]
}
```

chore(doc): hadolint 2.12.0

---

lib/main.sh
test/e2e.sh

Fixes: https://github.com/jbergstroem/hadolint-gh-action/issues/108

fix: silence output in version test

---

.github/renovate.json

This makes PR titles easier to follow.

chore: rename dependency

---

.github/workflows/lint.yml

Invoke Prettier from bun, speeds things up nicely.

chore(ci): switch from node to bun

---

install.sh

Move it after `set -x` so we can use DEBUG.

chore: move variable initialization

---

.github/workflows/test-e2e.yml
README.md
action.yml

Co-Authored-By: Thiago Perrotta <thiago@perrotta.dev>
Closes: https://github.com/jbergstroem/hadolint-gh-action/pull/161

chore: hadolint v2.13.1
